version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database
  database:
    image: mariadb:10.5
    env_file:
      - docker.env
    volumes:
      - ./mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    env_file:
      - docker.env
    depends_on:
      - database
